backend:
  name: git-gateway

media_folder: "/src/media/images"
public_folder: "/media/images/"

collections:
  - label: Pages
    name: pages
    description: List of pages
    folder: /src
    preview_path: /{{slug}}/
    extension: md
    create: true
    fields:
      - label: Layout
        name: layout
        widget: hidden
        default: Default.tsx
      - label: Title
        name: title
        widget: string
        editor:
          preview: false
      - label: Content
        name: body
        widget: markdown
      - label: Menu
        name: menu
        widget: object
        fields:
          - label: Header
            name: header
            widget: boolean
            required: false
            default: false
          - label: Footer
            name: footer
            widget: boolean
            required: false
            default: false
